-- Find the total customers by country

SELECT country, COUNT( DISTINCT customer_key) AS total_customers	
FROM `gold.dim_customers`
GROUP BY country
ORDER BY total_customers DESC
;
 
-- Find the total customers by gender

SELECT gender, COUNT(customer_key) AS total_customers
FROM `gold.dim_customers`
GROUP BY gender
ORDER BY total_customers DESC
;

-- Find the total products by category

SELECT category, COUNT(product_key) AS total_products
FROM `gold.dim_products`
GROUP BY category
ORDER BY total_products DESC
;

-- What is the average cost in each category

SELECT category, AVG(cost) avg_cost
FROM `gold.dim_products`
GROUP BY category
ORDER BY avg_cost DESC
;

-- What is the total revenue generated for each category

SELECT category, SUM(sales_amount) AS total_revenue
FROM `gold.fact_sales` f
LEFT JOIN `gold.dim_products` p
	ON f.product_key = p.product_key
GROUP BY category
ORDER BY total_revenue DESC
;

-- Find total revenue generated by each customer

SELECT 
c.customer_key, 
first_name, 
last_name,
SUM(sales_amount) AS total_revenue
FROM `gold.fact_sales` f
LEFT JOIN `gold.dim_customers` c
	ON f.customer_key = c.customer_key
GROUP BY 
c.customer_key, 
first_name, 
last_name
ORDER BY total_revenue DESC
;

-- What is the distribution of sold items across countries 

SELECT 
country,
SUM(quantity) AS items_sold
FROM `gold.fact_sales` f
LEFT JOIN `gold.dim_customers` c
	ON f.customer_key = c.customer_key
GROUP BY country
ORDER BY items_sold DESC
;










































